user store 모델 delete
swsnu/swppfall2022-team14 pull request #126
Opened 2022-11-19 09:19 UTC by AlongwithKiman

Resolves #125 
## 해결/개선하고자 한 기능 설명
- delete 구현
- frontend 적용

## 실제로 해결/개선한 방식
...

## 나중에 추가로 해결/개선해야하는 사항
...

2022-11-19 14:19 UTC, nemga123 approved these changes

2022-11-19 15:06 UTC, nemga123 requested changes
이 과정 id를 파람으로 받아서 하는 것 말고 session 기반 로그인 과정으로 해야하지 않을까요? 로그인이 되어야 얻을 수 있는 정보 같습니다.

2022-11-19 15:11 UTC, AlongwithKiman commented
더미 아이디 보내는 부분 말하신건가요?? 그래야 하긴 할 거 같습니다 ..

2022-11-21 05:47 UTC, nemga123 commented
더미데이터도 그렇고 url자체에 user_id없이 그냥 현재 로그인된 유저르 id를 가져와야할 것 같다는 말이었습니다.

2022-11-21 07:25 UTC, AlongwithKiman commented
일단 이 브랜치에서 백엔드 부분은 수정하였습니다.

2022-11-22 02:36 UTC, nemga123 approved these changes

2022-11-22 02:46 UTC, merged